package storage

import (
	"bytes"
	"context"
	"encoding/json"
	"io"
	"testing"

	"github.com/Rainminds/gantral/internal/artifact"
	"github.com/Rainminds/gantral/pkg/models"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/aws/aws-sdk-go-v2/service/s3/types"
	"github.com/aws/smithy-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
)

// MockS3Client is an autogenerated mock type for the S3ClientAPI type
type MockS3Client struct {
	mock.Mock
}

func (_m *MockS3Client) GetObject(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.Options)) (*s3.GetObjectOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetObject")
	}

	var r0 *s3.GetObjectOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *s3.GetObjectInput, ...func(*s3.Options)) (*s3.GetObjectOutput, error)); ok {
		return rf(ctx, params, optFns...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *s3.GetObjectInput, ...func(*s3.Options)) *s3.GetObjectOutput); ok {
		r0 = rf(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.GetObjectOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *s3.GetObjectInput, ...func(*s3.Options)) error); ok {
		r1 = rf(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *MockS3Client) PutObject(ctx context.Context, params *s3.PutObjectInput, optFns ...func(*s3.Options)) (*s3.PutObjectOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PutObject")
	}

	var r0 *s3.PutObjectOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *s3.PutObjectInput, ...func(*s3.Options)) (*s3.PutObjectOutput, error)); ok {
		return rf(ctx, params, optFns...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *s3.PutObjectInput, ...func(*s3.Options)) *s3.PutObjectOutput); ok {
		r0 = rf(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.PutObjectOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *s3.PutObjectInput, ...func(*s3.Options)) error); ok {
		r1 = rf(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func TestS3Store_WriteArtifact_Success(t *testing.T) {
	mockS3 := new(MockS3Client)
	store := NewS3Store(mockS3, "test-bucket", "artifacts")

	art := models.NewCommitmentArtifact("inst-1", "v1", "", "APPROVED", "pol-1", "hash", "user", "ok")

	mockS3.On("PutObject", mock.Anything, mock.MatchedBy(func(input *s3.PutObjectInput) bool {
		return *input.Bucket == "test-bucket" &&
			*input.IfNoneMatch == "*" &&
			*input.ContentType == "application/json"
	})).Return(&s3.PutObjectOutput{}, nil)

	err := store.WriteArtifact(context.Background(), "team-1", art)
	assert.NoError(t, err)
	mockS3.AssertExpectations(t)
}

func TestS3Store_WriteArtifact_WORM_Violation(t *testing.T) {
	mockS3 := new(MockS3Client)
	store := NewS3Store(mockS3, "test-bucket", "artifacts")

	art := models.NewCommitmentArtifact("inst-1", "v1", "", "APPROVED", "pol-1", "hash", "user", "ok")

	// Simulate S3 returning a PreconditionFailed when IfNoneMatch hits
	awsErr := &smithy.GenericAPIError{
		Code:    "PreconditionFailed",
		Message: "At least one of the pre-conditions you specified did not hold",
	}
	mockS3.On("PutObject", mock.Anything, mock.Anything).Return((*s3.PutObjectOutput)(nil), awsErr)

	err := store.WriteArtifact(context.Background(), "team-1", art)

	// Assert it maps correctly to the internal WORM domain error
	assert.ErrorIs(t, err, artifact.ErrImmutableViolation)
	mockS3.AssertExpectations(t)
}

func TestS3Store_GetArtifact_Success(t *testing.T) {
	mockS3 := new(MockS3Client)
	store := NewS3Store(mockS3, "test-bucket", "artifacts")

	art := models.NewCommitmentArtifact("inst-1", "v1", "", "APPROVED", "pol-1", "hash", "user", "ok")
	payload, _ := json.Marshal(art)

	mockS3.On("GetObject", mock.Anything, mock.MatchedBy(func(input *s3.GetObjectInput) bool {
		return *input.Bucket == "test-bucket"
	})).Return(&s3.GetObjectOutput{
		Body: io.NopCloser(bytes.NewReader(payload)),
	}, nil)

	retrieved, err := store.GetArtifact(context.Background(), "team-1", art.ArtifactHash)

	assert.NoError(t, err)
	assert.Equal(t, art.ArtifactID, retrieved.ArtifactID)
	assert.Equal(t, "APPROVED", retrieved.AuthorityState)
	mockS3.AssertExpectations(t)
}

func TestS3Store_GetArtifact_NotFound(t *testing.T) {
	mockS3 := new(MockS3Client)
	store := NewS3Store(mockS3, "test-bucket", "artifacts")

	awsErr := &types.NoSuchKey{}
	mockS3.On("GetObject", mock.Anything, mock.Anything).Return((*s3.GetObjectOutput)(nil), awsErr)

	_, err := store.GetArtifact(context.Background(), "team-1", "missing-hash")

	assert.ErrorIs(t, err, artifact.ErrArtifactNotFound)
	mockS3.AssertExpectations(t)
}
