// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID         string
	InstanceID string
	EventType  string
	Payload    []byte
	Timestamp  pgtype.Timestamptz
}

type Decision struct {
	ID              string
	InstanceID      string
	Type            string
	ActorID         string
	Justification   string
	Role            string
	ContextSnapshot []byte
	ContextDelta    []byte
	PolicyVersionID string
	CreatedAt       pgtype.Timestamptz
}

type Instance struct {
	ID               string
	WorkflowID       string
	State            string
	TriggerContext   []byte
	PolicyContext    []byte
	PolicyVersionID  string
	LastArtifactHash string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}
