// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const createAuditEvent = `-- name: CreateAuditEvent :one
INSERT INTO audit_events (
    id, instance_id, event_type, payload
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, instance_id, event_type, payload, timestamp
`

type CreateAuditEventParams struct {
	ID         string
	InstanceID string
	EventType  string
	Payload    []byte
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, createAuditEvent,
		arg.ID,
		arg.InstanceID,
		arg.EventType,
		arg.Payload,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.EventType,
		&i.Payload,
		&i.Timestamp,
	)
	return i, err
}

const createDecision = `-- name: CreateDecision :one
INSERT INTO decisions (
    id, instance_id, type, actor_id, justification, role, context_snapshot, context_delta, policy_version_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, instance_id, type, actor_id, justification, role, context_snapshot, context_delta, policy_version_id, created_at
`

type CreateDecisionParams struct {
	ID              string
	InstanceID      string
	Type            string
	ActorID         string
	Justification   string
	Role            string
	ContextSnapshot []byte
	ContextDelta    []byte
	PolicyVersionID string
}

func (q *Queries) CreateDecision(ctx context.Context, arg CreateDecisionParams) (Decision, error) {
	row := q.db.QueryRow(ctx, createDecision,
		arg.ID,
		arg.InstanceID,
		arg.Type,
		arg.ActorID,
		arg.Justification,
		arg.Role,
		arg.ContextSnapshot,
		arg.ContextDelta,
		arg.PolicyVersionID,
	)
	var i Decision
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Type,
		&i.ActorID,
		&i.Justification,
		&i.Role,
		&i.ContextSnapshot,
		&i.ContextDelta,
		&i.PolicyVersionID,
		&i.CreatedAt,
	)
	return i, err
}

const createInstance = `-- name: CreateInstance :one
INSERT INTO instances (
    id,
    workflow_id,
    state,
    trigger_context,
    policy_context,
    policy_version_id,
    last_artifact_hash
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, workflow_id, state, trigger_context, policy_context, policy_version_id, last_artifact_hash, created_at, updated_at
`

type CreateInstanceParams struct {
	ID               string
	WorkflowID       string
	State            string
	TriggerContext   []byte
	PolicyContext    []byte
	PolicyVersionID  string
	LastArtifactHash string
}

func (q *Queries) CreateInstance(ctx context.Context, arg CreateInstanceParams) (Instance, error) {
	row := q.db.QueryRow(ctx, createInstance,
		arg.ID,
		arg.WorkflowID,
		arg.State,
		arg.TriggerContext,
		arg.PolicyContext,
		arg.PolicyVersionID,
		arg.LastArtifactHash,
	)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.State,
		&i.TriggerContext,
		&i.PolicyContext,
		&i.PolicyVersionID,
		&i.LastArtifactHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuditEvents = `-- name: GetAuditEvents :many
SELECT id, instance_id, event_type, payload, timestamp FROM audit_events
WHERE instance_id = $1
ORDER BY timestamp ASC
`

func (q *Queries) GetAuditEvents(ctx context.Context, instanceID string) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, getAuditEvents, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.EventType,
			&i.Payload,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDecisionsByInstance = `-- name: GetDecisionsByInstance :many
SELECT id, instance_id, type, actor_id, justification, role, context_snapshot, context_delta, policy_version_id, created_at FROM decisions
WHERE instance_id = $1
`

func (q *Queries) GetDecisionsByInstance(ctx context.Context, instanceID string) ([]Decision, error) {
	rows, err := q.db.Query(ctx, getDecisionsByInstance, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Decision
	for rows.Next() {
		var i Decision
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.Type,
			&i.ActorID,
			&i.Justification,
			&i.Role,
			&i.ContextSnapshot,
			&i.ContextDelta,
			&i.PolicyVersionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInstance = `-- name: GetInstance :one
SELECT id, workflow_id, state, trigger_context, policy_context, policy_version_id, last_artifact_hash, created_at, updated_at FROM instances
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetInstance(ctx context.Context, id string) (Instance, error) {
	row := q.db.QueryRow(ctx, getInstance, id)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.State,
		&i.TriggerContext,
		&i.PolicyContext,
		&i.PolicyVersionID,
		&i.LastArtifactHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInstances = `-- name: ListInstances :many
SELECT id, workflow_id, state, trigger_context, policy_context, policy_version_id, last_artifact_hash, created_at, updated_at FROM instances
ORDER BY created_at DESC
`

func (q *Queries) ListInstances(ctx context.Context) ([]Instance, error) {
	rows, err := q.db.Query(ctx, listInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Instance
	for rows.Next() {
		var i Instance
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.State,
			&i.TriggerContext,
			&i.PolicyContext,
			&i.PolicyVersionID,
			&i.LastArtifactHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInstanceState = `-- name: UpdateInstanceState :exec
UPDATE instances
SET state = $2, last_artifact_hash = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateInstanceStateParams struct {
	ID               string
	State            string
	LastArtifactHash string
}

func (q *Queries) UpdateInstanceState(ctx context.Context, arg UpdateInstanceStateParams) error {
	_, err := q.db.Exec(ctx, updateInstanceState, arg.ID, arg.State, arg.LastArtifactHash)
	return err
}
