// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const createInstance = `-- name: CreateInstance :exec
INSERT INTO instances (
    id,
    workflow_id,
    state,
    trigger_context
) VALUES (
    $1, $2, $3, $4
)
`

type CreateInstanceParams struct {
	ID             string
	WorkflowID     string
	State          string
	TriggerContext []byte
}

func (q *Queries) CreateInstance(ctx context.Context, arg CreateInstanceParams) error {
	_, err := q.db.Exec(ctx, createInstance,
		arg.ID,
		arg.WorkflowID,
		arg.State,
		arg.TriggerContext,
	)
	return err
}

const getInstance = `-- name: GetInstance :one
SELECT id, workflow_id, state, trigger_context, created_at, updated_at FROM instances
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetInstance(ctx context.Context, id string) (Instance, error) {
	row := q.db.QueryRow(ctx, getInstance, id)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.State,
		&i.TriggerContext,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateState = `-- name: UpdateState :exec
UPDATE instances
SET state = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateStateParams struct {
	ID    string
	State string
}

func (q *Queries) UpdateState(ctx context.Context, arg UpdateStateParams) error {
	_, err := q.db.Exec(ctx, updateState, arg.ID, arg.State)
	return err
}
